version: "2"

services:

# ------> asset ------>
    asset_4awb1kgyjlxxllo9:
        container_name: asset_4awb1kgyjlxxllo9
        image: node:alpine
        working_dir: /var/www/assets
        volumes:
            - ../assets:/var/www/assets
            - ../public:/var/www/public
# <------ asset <------